//! Данные классификатора: расширение → категория и паттерны кэш-папок.
//! Сгенерировано как контент-таблица (тикет 001). Только данные, без логики.

use crate::ipc::contract::Category;

/// Пары (расширение_без_точки_в_нижнем_регистре, категория).
/// Отсортировано по категории, внутри — по алфавиту. Без дубликатов расширений.
pub const EXTENSION_CATEGORY: &[(&str, Category)] = &[
    ("7z", Category::Archive),
    ("apk", Category::Archive),
    ("arj", Category::Archive),
    ("bz2", Category::Archive),
    ("cab", Category::Archive),
    ("cpio", Category::Archive),
    ("dmg", Category::Archive),
    ("ear", Category::Archive),
    ("gz", Category::Archive),
    ("iso", Category::Archive),
    ("jar", Category::Archive),
    ("lzma", Category::Archive),
    ("pkg", Category::Archive),
    ("rar", Category::Archive),
    ("tar", Category::Archive),
    ("tbz2", Category::Archive),
    ("tgz", Category::Archive),
    ("war", Category::Archive),
    ("xz", Category::Archive),
    ("z", Category::Archive),
    ("zip", Category::Archive),
    ("zipx", Category::Archive),
    ("aac", Category::Audio),
    ("aif", Category::Audio),
    ("aiff", Category::Audio),
    ("alac", Category::Audio),
    ("ape", Category::Audio),
    ("flac", Category::Audio),
    ("m4a", Category::Audio),
    ("mid", Category::Audio),
    ("midi", Category::Audio),
    ("mp3", Category::Audio),
    ("ogg", Category::Audio),
    ("opus", Category::Audio),
    ("wav", Category::Audio),
    ("wma", Category::Audio),
    ("a", Category::Binary),
    ("accdb", Category::Binary),
    ("bin", Category::Binary),
    ("dat", Category::Binary),
    ("db", Category::Binary),
    ("deb", Category::Binary),
    ("dll", Category::Binary),
    ("dmp", Category::Binary),
    ("dylib", Category::Binary),
    ("elf", Category::Binary),
    ("exe", Category::Binary),
    ("img", Category::Binary),
    ("lib", Category::Binary),
    ("mdb", Category::Binary),
    ("msi", Category::Binary),
    ("o", Category::Binary),
    ("obj", Category::Binary),
    ("pdb", Category::Binary),
    ("qcow2", Category::Binary),
    ("rpm", Category::Binary),
    ("so", Category::Binary),
    ("sqlite", Category::Binary),
    ("sqlite3", Category::Binary),
    ("sqlitedb", Category::Binary),
    ("sys", Category::Binary),
    ("vdi", Category::Binary),
    ("vhd", Category::Binary),
    ("vhdx", Category::Binary),
    ("vmdk", Category::Binary),
    ("asm", Category::Code),
    ("bat", Category::Code),
    ("c", Category::Code),
    ("cfg", Category::Code),
    ("cmake", Category::Code),
    ("cmd", Category::Code),
    ("conf", Category::Code),
    ("cpp", Category::Code),
    ("cs", Category::Code),
    ("css", Category::Code),
    ("cxx", Category::Code),
    ("dart", Category::Code),
    ("dockerfile", Category::Code),
    ("fs", Category::Code),
    ("go", Category::Code),
    ("gradle", Category::Code),
    ("groovy", Category::Code),
    ("h", Category::Code),
    ("hpp", Category::Code),
    ("hs", Category::Code),
    ("html", Category::Code),
    ("ini", Category::Code),
    ("java", Category::Code),
    ("js", Category::Code),
    ("json", Category::Code),
    ("jsx", Category::Code),
    ("kt", Category::Code),
    ("kts", Category::Code),
    ("less", Category::Code),
    ("lua", Category::Code),
    ("makefile", Category::Code),
    ("mjs", Category::Code),
    ("php", Category::Code),
    ("pl", Category::Code),
    ("ps1", Category::Code),
    ("py", Category::Code),
    ("r", Category::Code),
    ("rb", Category::Code),
    ("rs", Category::Code),
    ("sass", Category::Code),
    ("scala", Category::Code),
    ("scss", Category::Code),
    ("sh", Category::Code),
    ("sql", Category::Code),
    ("swift", Category::Code),
    ("toml", Category::Code),
    ("ts", Category::Code),
    ("tsx", Category::Code),
    ("xml", Category::Code),
    ("yaml", Category::Code),
    ("yml", Category::Code),
    ("bib", Category::Document),
    ("csv", Category::Document),
    ("djvu", Category::Document),
    ("doc", Category::Document),
    ("docx", Category::Document),
    ("epub", Category::Document),
    ("fb2", Category::Document),
    ("key", Category::Document),
    ("log", Category::Document),
    ("markdown", Category::Document),
    ("md", Category::Document),
    ("mdx", Category::Document),
    ("mobi", Category::Document),
    ("numbers", Category::Document),
    ("odp", Category::Document),
    ("ods", Category::Document),
    ("odt", Category::Document),
    ("pages", Category::Document),
    ("pdf", Category::Document),
    ("ppt", Category::Document),
    ("pptx", Category::Document),
    ("rtf", Category::Document),
    ("tex", Category::Document),
    ("tsv", Category::Document),
    ("txt", Category::Document),
    ("xls", Category::Document),
    ("xlsx", Category::Document),
    ("ai", Category::Image),
    ("bmp", Category::Image),
    ("eps", Category::Image),
    ("fig", Category::Image),
    ("gif", Category::Image),
    ("heic", Category::Image),
    ("heif", Category::Image),
    ("ico", Category::Image),
    ("indd", Category::Image),
    ("jpeg", Category::Image),
    ("jpg", Category::Image),
    ("png", Category::Image),
    ("psd", Category::Image),
    ("raw", Category::Image),
    ("sketch", Category::Image),
    ("svg", Category::Image),
    ("tif", Category::Image),
    ("tiff", Category::Image),
    ("webp", Category::Image),
    ("xcf", Category::Image),
    ("3gp", Category::Video),
    ("asf", Category::Video),
    ("avi", Category::Video),
    ("divx", Category::Video),
    ("flv", Category::Video),
    ("m2ts", Category::Video),
    ("m4v", Category::Video),
    ("mkv", Category::Video),
    ("mov", Category::Video),
    ("mp4", Category::Video),
    ("mpeg", Category::Video),
    ("mpg", Category::Video),
    ("mts", Category::Video),
    ("ogv", Category::Video),
    ("rm", Category::Video),
    ("rmvb", Category::Video),
    ("vob", Category::Video),
    ("webm", Category::Video),
    ("wmv", Category::Video),
];

/// Имена каталогов, которые обычно являются кэшем/мусором (кандидаты на очистку).
/// Имена сравниваются по точному совпадению имени каталога в нижнем регистре.
pub const CLEANUP_DIR_NAMES: &[&str] = &[
    // Корзины ОС (в корне каждого диска Windows; `.trash` — задел под *nix).
    // Подпапки с UID (`.trash-1000`) пока не ловим — нужен префиксный матч.
    "$recycle.bin",
    ".cache",
    ".gradle",
    ".idea",
    ".ipynb_checkpoints",
    ".pytest_cache",
    ".sass-cache",
    ".trash",
    ".turbo",
    ".venv",
    ".vs",
    "__pycache__",
    "bower_components",
    "build",
    "dist",
    "node_modules",
    "out",
    "target",
    "temp",
    "tmp",
    "venv",
];
